// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuucHo78WRlqbSj3zrcwd_wEtcYHxi9Xg',
    appId: '1:766893512721:web:1f8bddaa006adf6169b9b0',
    messagingSenderId: '766893512721',
    projectId: 'levity-6ab80',
    authDomain: 'levity-6ab80.firebaseapp.com',
    storageBucket: 'levity-6ab80.firebasestorage.app',
    measurementId: 'G-SF32M8JKL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh8n1F9mangmCph4QThUXBNG75dHq20-o',
    appId: '1:766893512721:android:4c4bde14d23219a369b9b0',
    messagingSenderId: '766893512721',
    projectId: 'levity-6ab80',
    storageBucket: 'levity-6ab80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbimBXc8qXvyH1EctU8zaovOmdElgnazo',
    appId: '1:766893512721:ios:dde2da2cb94551ae69b9b0',
    messagingSenderId: '766893512721',
    projectId: 'levity-6ab80',
    storageBucket: 'levity-6ab80.firebasestorage.app',
    iosClientId: '766893512721-f72m06b42bp7ercal1o9f3ph2lmrkkgc.apps.googleusercontent.com',
    iosBundleId: 'com.antigravityhealth.app.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbimBXc8qXvyH1EctU8zaovOmdElgnazo',
    appId: '1:766893512721:ios:dde2da2cb94551ae69b9b0',
    messagingSenderId: '766893512721',
    projectId: 'levity-6ab80',
    storageBucket: 'levity-6ab80.firebasestorage.app',
    iosClientId: '766893512721-f72m06b42bp7ercal1o9f3ph2lmrkkgc.apps.googleusercontent.com',
    iosBundleId: 'com.antigravityhealth.app.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuucHo78WRlqbSj3zrcwd_wEtcYHxi9Xg',
    appId: '1:766893512721:web:c3be8a038f870df669b9b0',
    messagingSenderId: '766893512721',
    projectId: 'levity-6ab80',
    authDomain: 'levity-6ab80.firebaseapp.com',
    storageBucket: 'levity-6ab80.firebasestorage.app',
    measurementId: 'G-P3X4Q97K5Z',
  );
}
